routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'HomeController@index')->name('home');
Route::get('/dashboard', 'HomeController@index');
Route::post('/dashboard/registrasiCheck', 'AsesorController@checkDuplicate')->name('instansi_duplicate.check');
Route::post('/dashboard/unitCheck','UnitKompetensiController@unitCheck');
//Statistik Export
Route::get('/dashboard/export-rekap-instansi','HomeController@RekapInstansi');
Route::get('/dashboard/export-skema-kompeten','HomeController@SkemaKompeten');
Route::get('/dashboard/export-skema-non-kompeten','HomeController@SkemaNonKompeten');
Route::get('/dashboard/export-asesi-non-kompeten','HomeController@AsesiNonKompeten');
Route::get('/dashboard/export-unit-kompeten','HomeController@UnitKompeten');
Route::get('/dashboard/export-unit-non-kompeten','HomeController@UnitNonKompeten');


Route::group(['middleware' => ['auth', 'admin']], function() {
    /**Master Data */
    Route::resource('/dashboard/kota','KotaController');
    Route::match(['put', 'patch'], '/dashboard/kota/store-update/{id}','KotaController@update');
    Route::resource('/dashboard/instansi','InstansiController');
    Route::resource('/dashboard/provinsi','ProvinsiController');
    Route::post('/dashboard/instansiCheck', 'InstansiController@checkDuplicate')->name('instansi_duplicate.check');
    Route::resource('/dashboard/kategori','KategoriKomponenController');
    Route::resource('/dashboard/kegiatan','KegiatanController');
    /* User */
    Route::resource('/dashboard/user','UserController');
    Route::post('/cekoldpassword','UserController@checkOldPassword');
});
Route::get('/dashboard/getkota/{id}', 'InstansiController@getKota');
Route::get('/dashboard/getAsesiBySkema/{id_skema}', 'HasilUjikomController@getAsesiBySkema');
Route::get('/dashboard/getUnitBySkema/{id_skema}', 'HasilUjikomController@getUnitBySkema');
Route::post('/dashboard/getUnitSurveilans','SurveilansController@getUnitSurveilans');

Route::group(['middleware' => ['auth', 'admin_jabatan']], function() {
    /* Asesi */
    Route::resource('/dashboard/asesi','AsesiController');
    Route::post('/dashboard/asesi/post', 'AsesiController@store');
    Route::resource('/dashboard/apl02','APL02Controller');
    Route::get('/dashboard/getAsesiSkemaAPL02/{id}','APL02Controller@getAsesiSkemaAPL02');
    Route::get('/dashboard/getSkemaUnitPertanyaan/{id}','APL02Controller@getSkemaUnitPertanyaan');
    /* Asesor */
    Route::resource('/dashboard/asesor','AsesorController');
    Route::post('/dashboard/asesor/post', 'AsesorController@store');
    Route::get('/dashboard/penugasan-asesor','PenugasanAsesorController@index');
    Route::get('/dashboard/penugasan-asesor/create/{id}','PenugasanAsesorController@create');
    Route::get('/dashboard/penugasan-asesor/show/{id}','PenugasanAsesorController@show');
    Route::post('/dashboard/penugasan-asesor/store','PenugasanAsesorController@store');
    Route::delete('/dashboard/penugasan-asesor/destroy/{id}','PenugasanAsesorController@destroy');
    
    /* Feedback */
    Route::resource('/dashboard/feedback','FeedbackController');
    Route::get('/dashboard/feedback/masukan/{id}','FeedbackController@create');
    Route::resource('/dashboard/komponen-feedback','KomponenFeedbackController');
    Route::get('/dashboard/feedback-asesi/{id}','FeedbackController@showAsesi');
    
    /* Ujikom */
    Route::resource('/dashboard/ujikom','UjikomController');
    Route::resource('/dashboard/unit-ujikom','UnitKompetensiController');
    
    Route::get('/dashboard/ujikom-hasil','HasilUjikomController@index');
    Route::get('/dashboard/ujikom-hasil/masukan/{id}','HasilUjikomController@create');
    Route::get('/dashboard/ujikom-hasil/detail/{id}','HasilUjikomController@show');
    Route::post('/dashboard/ujikom-hasil/post','HasilUjikomController@store');
   
    
    Route::resource('/dashboard/skema-ujikom','SkemaController');
    Route::post('/dashboard/insert-unit-skema', 'SkemaController@insertUnitSkema');
    Route::delete('/dashboard/destroy-unit-skema/{id}','SkemaController@destroyUnitSkema');
    
    Route::get('/dashboard/ujikom-skema-set/{id}','UjikomController@setUjikomSkema');
    Route::post('/dashboard/ujikom-skema-store/','UjikomController@storeUjikomSkema');
    Route::delete('/dashboard/ujikom-skema-destroy/{id}','UjikomController@destroyUjikomSkema');
    
    Route::get('/dashboard/ujikom-add-asesor/{id}','UjikomController@AddAsesor');
    Route::post('/dashboard/ujikom-add-asesor/post','UjikomController@storeAddAsesor');
    Route::get('/dashboard/ujikom-add-asesi/{id}','UjikomController@AddAsesi');
    Route::post('/dashboard/ujikom-add-asesi/post','UjikomController@storeAddAsesi');
    
    Route::get('/dashboard/unit-pertanyaan/{id}','PertanyaanUnitController@index');
    Route::post('/dashboard/unit-pertanyaan/store','PertanyaanUnitController@store');
    Route::delete('/dashboard/unit-pertanyaan/destroy/{id}','PertanyaanUnitController@destroy');

    Route::resource('/dashboard/ujikom-banding','BandingMAK02Controller');
    Route::resource('/dashboard/ujikom-persetujuan','PersetujuanController');
    Route::resource('/dashboard/asesmen-peninjauan','PeninjauanAsesmenController');
    Route::resource('/dashboard/asesmen-keputusan','KeputusanController');
    Route::resource('/dashboard/ceklis-kompetensi','CeklisMAK01Controller');
    /** Surveilans **/
    Route::resource('/dashboard/surveilans','SurveilansController');
});
Route::group(['middleware' => ['auth', 'admin_sertifikat']], function() {
    /** Sertifikat */
    Route::resource('/dashboard/sertifikat','SertifikatController');
    Route::resource('/dashboard/pengiriman-sertifikat','PengirimanSertifikatController');
    Route::get('/dashboard/tracking-sertifikat','TrackingSertifikatController@index');
    Route::get('/dashboard/tracking-sertifikat/result','TrackingSertifikatController@track');
    Route::get('/dashboard/sertifikat-export','SertifikatController@export');
    Route::get('/dashboard/sertifikat-export/{id}','SertifikatController@exportByUjikom');
    Route::get('/dashboard/get-tanggal/{id}','PengirimanSertifikatController@getTanggalSertifikat');

});

Route::get('/sendbasicemail','MailController@basic_email');
Route::get('/sendhtmlemail','MailController@html_email');
Route::get('/sendattachmentemail','MailController@attachment_email');

Auth::routes();

resources/views/dashboard/asesor-default.blade.php
@extends('dashboard.layout')
@section('content')
       <!-- page content -->
       <div class="right_col" role="main">
          <div class="">
          <div class="row top_tiles">
              <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="tile-stats">
                  <div class="icon"><i class="fa fa-user"></i></div>
                  <div class="count">{{$count_int_active}}</div>
                  <h3 style="font-size:20px"> Asesor Internal Aktif</h3>
                  
                </div>
              </div>
              <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="tile-stats">
                  <div class="icon"><i class="fa fa-user"></i></div>
                  <div class="count">{{$count_int_inactive}}</div>
                  <h3 style="font-size:20px"> Asesor Internal Non-Aktif</h3>
                  
                </div>
              </div>
              <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="tile-stats">
                  <div class="icon"><i class="fa fa-user"></i></div>
                  <div class="count">{{$count_ext_active}}</div>
                  <h3 style="font-size:20px"> Asesor Eksternal Aktif</h3>
                  
                </div>
              </div>
              <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="tile-stats">
                  <div class="icon"><i class="fa fa-user"></i></div>
                  <div class="count">{{$count_ext_inactive}}</div>
                  <h3 style="font-size:20px"> Asesor Eksternal Non-Aktif</h3>
                  
                </div>
              </div>

            <div class="clearfix"></div>
            <a class="btn btn-success" href="/dashboard/asesor/create">Masukan Data Asesor</a>
           
            <div class="row">
                  @if ($message = Session::get('success'))
                      <div class="alert alert-success">
                          <p>{{ $message }}</p>
                      </div>
                  @endif
                  @if ($message = Session::get('error'))
                      <div class="alert alert-danger">
                          <p>{{ $message }}</p>
                      </div>
                  @endif
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Daftar Asesor</h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                     
                      
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                  
                    <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                      <thead>
                        <tr>
                          <th>#</th>
                          <th>Nama</th>
                          <th>Jenis Kelamin</th>
                          <th>Instansi</th>
                          <th>Kota</th>
                          <th>Jenis Asesor</th>
                          <th>Masa Berlaku</th>
                          <th>Status</th>
                          <th>Action</th>
                        </tr>
                      </thead>
                      <tbody>
                      @foreach ($asesors as $asesor)
                        <tr>
                            <td>{{ ++$loop->index }}</td>
                            <td>{{ $asesor->nama}}</td>
                            <td>@if ($asesor->jenis_kelamin === 'L')
                                    Laki-Laki
                                @else
                                  Perempuan
                                @endif</td>
                            <td>{{ $asesor->nama_instansi}}</td>
                            <td>{{ $asesor->nama_kota}}</td>
                            <td>{{ $asesor->jenis_asesor}}</td>
                            <td>{{ $asesor->masa_berlaku}}</td>
                            <td>@if ($asesor->is_active === 1)
                                    Aktif
                                @else
                                  Non-Aktif
                                @endif</td>
                            
                            <td>
                              <a class="btn btn-success" href="{{ route('asesor.show',$asesor->id) }}">Detail</a>
                              <a class="btn btn-primary" href="{{ route('asesor.edit',$asesor->id) }}">Edit</a>
                              <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#myModal">
                                Hapus 
                              </button>
                            </td>
                        </tr>
                        @endforeach
                        
                        
                      
                      </tbody>
                    </table>
					  <!-- The Modal -->
            <div class="modal fade" id="myModal">
                    <div class="modal-dialog">
                      <div class="modal-content">

                        <!-- Modal Header -->
                        <div class="modal-header">
                          <h4 class="modal-title">Konfirmasi</h4>
                          <button type="button" class="close" data-dismiss="modal">&times;</button>
                        </div>

                        <!-- Modal body -->
                        <div class="modal-body">
                          <h5>Apakah anda yakin ingin menghapus?</h5>
                        </div>

                        <!-- Modal footer -->
                        <div class="modal-footer">
                        <form action="{{ route('asesor.destroy',$asesor->id) }}" method="POST">
                            @csrf
                            @method('DELETE')
              
                            <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                        </div>

                      </div>
                    </div>
                  </div>
					
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- /page content -->
        <!-- jQuery -->
    <script src="/vendors/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- FastClick -->
    <script src="/vendors/fastclick/lib/fastclick.js"></script>
    <!-- NProgress -->
    <script src="/vendors/nprogress/nprogress.js"></script>
    <!-- iCheck -->
    <script src="/vendors/iCheck/icheck.min.js"></script>
    <!-- Datatables -->
    <script src="/vendors/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    <script src="/vendors/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
    <script src="/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js"></script>
    <script src="/vendors/datatables.net-buttons/js/buttons.flash.min.js"></script>
    <script src="/vendors/datatables.net-buttons/js/buttons.html5.min.js"></script>
    <script src="/vendors/datatables.net-buttons/js/buttons.print.min.js"></script>
    <script src="/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>
    <script src="/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
    <script src="/vendors/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
    <script src="/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js"></script>
    <script src="/vendors/datatables.net-scroller/js/dataTables.scroller.min.js"></script>
    <script src="/vendors/jszip/dist/jszip.min.js"></script>
    <script src="/vendors/pdfmake/build/pdfmake.min.js"></script>
    <script src="/vendors/pdfmake/build/vfs_fonts.js"></script>

    <!-- Custom Theme Scripts -->
    <script src="/build/js/custom.min.js"></script>
    
@endsection

resources/views/dashboard/banding-mak02-default.blade.php
@extends('dashboard.layout')
@section('content')
       <!-- page content -->
       <div class="right_col" role="main">
          <div class="">
          <a class="btn btn-success" href="/dashboard/ujikom-banding/create">Masukan Data MAK02</a>
          
            <div class="clearfix"></div>
            <div class="row">
                  @if ($message = Session::get('success'))
                      <div class="alert alert-success">
                          <p>{{ $message }}</p>
                      </div>
                  @endif
                  @if ($message = Session::get('error'))
                      <div class="alert alert-danger">
                          <p>{{ $message }}</p>
                      </div>
                  @endif
       
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Rekap Asesi</h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                     
                      
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                  
                    <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                      <thead>
                        <tr>
                          <th>ID</th>
                          <th>Nama Asesor</th>
                          <th>Nama Asesi </th>
                          <th>Nama Unit Kompetensi</th>
                          <th>Alasan Banding</th>
                          <th>Tanggal Asesmen</th>
                          <th>Action</th>
                        </tr>
                      </thead>
                      <tbody>
                      @foreach ($banding as $banding)
                        <tr>
                            <td>{{ $banding->id }}</td>
                            <td>{{ $banding->asesor}}</td>
                            <td>{{ $banding->asesi}}</td>
                            <td>{{ $banding->nama_unit_kompetensi}}</td>
                            <td>{{ $banding->alasan_banding}}</td>
                            <td>{{ $banding->tanggal_asesmen}}</td>
                      
                            <td>
                                    <a class="btn btn-success" href="{{ route('ujikom-banding.show',$banding->id) }}">Detail</a>
                                                
                                    <a class="btn btn-primary" href="{{ route('ujikom-banding.edit',$banding->id) }}">Edit</a>
                                    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#myModal">
                                      Hapus 
                                    </button>
                            </td>
                        </tr>
                        @endforeach
                        
                        
                      
                      </tbody>
                    </table>
                  @if($count>0)
                  <!-- The Modal -->
                  <div class="modal fade" id="myModal">
                    <div class="modal-dialog">
                      <div class="modal-content">

                        <!-- Modal Header -->
                        <div class="modal-header">
                          <h4 class="modal-title">Konfirmasi</h4>
                          <button type="button" class="close" data-dismiss="modal">&times;</button>
                        </div>

                        <!-- Modal body -->
                        <div class="modal-body">
                          <h5>Apakah anda yakin ingin menghapus?</h5>
                        </div>

                        <!-- Modal footer -->
                        <div class="modal-footer">
                        <form action="{{ route('ujikom-banding.destroy',$banding->id) }}" method="POST">
                            @csrf
                            @method('DELETE')
              
                            <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                        </div>

                      </div>
                    </div>
                  </div>
					        @endif
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- /page content -->
        <!-- jQuery -->
        <script src="/vendors/jquery/dist/jquery.min.js"></script>
        <!-- Bootstrap -->
        <script src="/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
        <!-- FastClick -->
        <script src="/vendors/fastclick/lib/fastclick.js"></script>
        <!-- NProgress -->
        <script src="/vendors/nprogress/nprogress.js"></script>
        <!-- iCheck -->
        <script src="/vendors/iCheck/icheck.min.js"></script>
        <!-- Datatables -->
        <script src="/vendors/datatables.net/js/jquery.dataTables.min.js"></script>
        <script src="/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
        <script src="/vendors/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
        <script src="/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js"></script>
        <script src="/vendors/datatables.net-buttons/js/buttons.flash.min.js"></script>
        <script src="/vendors/datatables.net-buttons/js/buttons.html5.min.js"></script>
        <script src="/vendors/datatables.net-buttons/js/buttons.print.min.js"></script>
        <script src="/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>
        <script src="/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
        <script src="/vendors/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
        <script src="/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js"></script>
        <script src="/vendors/datatables.net-scroller/js/dataTables.scroller.min.js"></script>
        <script src="/vendors/jszip/dist/jszip.min.js"></script>
        <script src="/vendors/pdfmake/build/pdfmake.min.js"></script>
        <script src="/vendors/pdfmake/build/vfs_fonts.js"></script>

    <!-- Custom Theme Scripts -->
    <script src="/build/js/custom.min.js"></script>
@endsection

resources/views/dashboard/skema-default.blade.php
@extends('dashboard.layout')
@section('content')
       <!-- page content -->
       <div class="right_col" role="main">
          <div class="">
          <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Masukan Data Skema Kompetensi</h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  @if ($message = Session::get('success'))
                      <div class="alert alert-success">
                          <p>{{ $message }}</p>
                      </div>
                  @endif
                  @if ($message = Session::get('error'))
                      <div class="alert alert-danger">
                          <p>{{ $message }}</p>
                      </div>
                  @endif
                  @if ($errors->any())
                      <div class="alert alert-danger">
                          <strong>Whoops!</strong> There were some problems with your input.<br><br>
                          <ul>
                              @foreach ($errors->all() as $error)
                                  <li>{{ $error }}</li>
                              @endforeach
                          </ul>
                      </div>
                  @endif
                  <div class="x_content">
                    <br />
                    <form method="POST" action="{{ route('skema-ujikom.store') }}" data-parsley-validate class="form-horizontal form-label-left">
                      @csrf
                      
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="nama_skema">Nama Skema <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          <input type="text" id="nama_skema" name="nama_skema" required="required" class="form-control col-md-7 col-xs-12">
                        </div>
                      </div>
                                    
                   
                      <div class="ln_solid"></div>
                      <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                          <button class="btn btn-primary" type="reset">Reset</button>
                          <button type="submit" class="btn btn-success">Simpan Data</button>
                        </div>
                      </div>

                    </form>
                  
                  </div>
                </div>
              </div>
            </div>
            <div class="clearfix"></div>

            <div class="row">
              
       
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Daftar Skema Kompetensi</h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                     
                      
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                  
                    <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                      <thead>
                        <tr>
                          <th>#</th>
                          <th>ID Skema</th>
                          <th>Nama Skema</th>
                          
                          <th>Action</th>
                        </tr>
                      </thead>
                      <tbody>
                      @foreach ($skema as $skema)
                        <tr>
                            <td>{{ ++$loop->index }}</td>
                            <td>{{ $skema->id }}</td>
                            <td>{{ $skema->nama_skema }}</td>
                            <td>
                              <a class="btn btn-success" href="{{ route('skema-ujikom.show',$skema->id) }}">Atur Unit Kompetensi per Skema</a>
                              <a class="btn btn-primary" href="{{ route('skema-ujikom.edit',$skema->id) }}">Edit</a>
                              <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#myModal">
                                Hapus 
                              </button>
                            </td>
                        </tr>
                        @endforeach
                        
                      
                      </tbody>
                    </table>
                    <div class="modal fade" id="myModal">
                    <div class="modal-dialog">
                      <div class="modal-content">

                        <!-- Modal Header -->
                        <div class="modal-header">
                          <h4 class="modal-title">Konfirmasi</h4>
                          <button type="button" class="close" data-dismiss="modal">&times;</button>
                        </div>

                        <!-- Modal body -->
                        <div class="modal-body">
                          <h5>Apakah anda yakin ingin menghapus?</h5>
                        </div>

                        <!-- Modal footer -->
                        <div class="modal-footer">
                        @if($count>0)
                        <form action="{{ route('skema-ujikom.destroy',$skema->id) }}" method="POST">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                        @endif
                        </div>

                      </div>
                    </div>
                  </div>
					
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- /page content -->
        <!-- jQuery -->
    <script src="/vendors/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- FastClick -->
    <script src="/vendors/fastclick/lib/fastclick.js"></script>
    <!-- NProgress -->
    <script src="/vendors/nprogress/nprogress.js"></script>
    <!-- iCheck -->
    <script src="/vendors/iCheck/icheck.min.js"></script>
    <!-- Datatables -->
    <script src="/vendors/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    <script src="/vendors/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
    <script src="/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js"></script>
    <script src="/vendors/datatables.net-buttons/js/buttons.flash.min.js"></script>
    <script src="/vendors/datatables.net-buttons/js/buttons.html5.min.js"></script>
    <script src="/vendors/datatables.net-buttons/js/buttons.print.min.js"></script>
    <script src="/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>
    <script src="/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
    <script src="/vendors/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
    <script src="/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js"></script>
    <script src="/vendors/datatables.net-scroller/js/dataTables.scroller.min.js"></script>
    <script src="/vendors/jszip/dist/jszip.min.js"></script>
    <script src="/vendors/pdfmake/build/pdfmake.min.js"></script>
    <script src="/vendors/pdfmake/build/vfs_fonts.js"></script>

    <!-- Custom Theme Scripts -->
    <script src="/build/js/custom.min.js"></script>

@endsection